# Generated by Django 5.1.3 on 2024-12-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twieetPost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twieetmodel',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
